### ISSUE TITLE
Sound set to looping is stacking. 

### ISSUE THREAD

**Issue by kyperbelt** [DatLycan/AMP#1]
Hey there, 

When I set up the AMP node up with a single stem using OGG background music files, I get a stacking playback. The track will add more and more streams at certain intervals. 

I narrowed it down to this line of code in the `add` function: 

```gd
for timestamp in timestamps:
	_daw.audio_track_insert_key(index, timestamp, stream)
```
> This is when set to LOOPING

it seems to be adding a bunch of keyframes to the audio track. I am wondering if this is the intended behavior. I will admit that I am not very musically inclined, so I am unsure what the reasoning for adding all these is. I removed them and only added a single  entry using `measure.next().y` but because I don't know what the indented behavior is supposed to be I am not sure if this was the right approach. Any feedback would be appreciated. 

I am running on Godot 4.03 C#.

**Comment by DatLycan** [comment]
Hi there! 
Setting all those keyframes is indeed the intended behavior. It is to make sure that the track plays in loop and even if you don't use a .wav file which has looping behavior in-built. 

The problem very likely stems from either:
- Not setting the BPM of the track up in the inspector
- Mismatching audio stem length

Make sure that your OGG file has the corresponding length. 
Or if you only want it to play once. 
Add a preset to your stem and set the `Playback Mode` to `Oneshot`.

**Comment by kyperbelt** [comment]
Alright, Thanks. I will try and play around with the BPM. I do want the sound to loop since its background music. Its about a 3 minute long track and I had set the bpm to around 110. I printed the timestamps and in the function up above and it looks like it added a new keyframe every few seconds.

**Comment by DatLycan** [comment]
Yes that is correct. Usually a stem is no longer than a single measure. 
If you have a track that has all the instruments included already it might be more efficient to simply use an AudioStreamPlayer instead ^^
